---
title: Rmd Test
author: ~
date: '2021-11-18'
slug: rmd-test
categories: []
tags: []
---


```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(plotly)
contracts <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/contracts_gender_r_2.xlsx")
defs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/defs_r.xlsx")
plfs <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/plfs_r.xlsx")
parties <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/parties_r.xlsx")
cites <- read_excel("/Users/professorserrano/Desktop/Documents/Video Essays/Law/cites_for_contracts.xlsx")

parties <- parties %>%
  full_join(cites)
```



```{r, echo = FALSE, warning = FALSE, message = FALSE}
contracts %>%
  group_by(year) %>%
  count() %>%
  ggplot() +
  geom_point(mapping=aes(year,n),alpha = 0.5, size = 3, position = position_jitter(w = 0, h = 0.1)) + 
  labs(title = "Distribution of Cases over Time")


contracts %>%
  group_by(year) %>%
  ggplot() +
  geom_bar(mapping=aes(year)) +
  labs(title = "Number of Cases by Year")


contracts %>%
  group_by(year) %>%
  ggplot() +
  geom_histogram(mapping=aes(year,fill = transaction),breaks = c(1820,1830,1840,1850,1860,1870,1880,1890,1900,1910,1920,1930,1940, 1950, 1960,1970,1980,1990,2000,2010,2020)) +
  labs(title = "Number of Cases by Decade")

names(cites) <- c("page","cite")
parties <- parties %>%
  full_join(cites, by = "page")

contracts %>%
  filter(transaction == "Property") %>%
  select(transaction, page, cite)

contracts %>%
  filter(year < 2000)

73 / 103
names(contracts)

parties %>%
  filter(transaction == "Family",spouse == "N") 
```



```{r, echo = FALSE, warning = FALSE, message = FALSE}

parties %>%
  filter(typenomf == "Woman" | typenomf == "Man" | typenomf == "Business") %>%
  ggplot() +
  geom_bar(mapping = aes(transaction,fill = typenomf)) +
  scale_fill_brewer(palette = 14) +
  theme_bw()

parties %>%
  filter(typenomf == "Woman" | typenomf == "Man") %>%
  ggplot() +
  geom_bar(mapping = aes(transaction,fill = typenomf)) +
  scale_fill_brewer(palette = 18) +
  theme_bw()


parties %>%
  filter(typenomf == "Business" ) %>%
  ggplot() +
  geom_bar(mapping = aes(transaction,fill = typenomf)) +
  scale_fill_brewer(palette = 9) +
  theme_bw()


parties %>%
  filter(typenomf == "Woman" | typenomf == "Man" ) %>%
  filter(spouse == "N") %>%
  ggplot() +
  geom_bar(mapping = aes(transaction,fill = typenomf)) +
  scale_fill_brewer(palette = 9) +
  theme_bw()


parties %>%
  filter(typenomf == "Woman") %>%
  filter(spouse == "N") %>%
  ggplot() +
  geom_bar(aes(year))
```


Gender graphs number of people per year with family status color 
bigger dots

```{r, echo = FALSE, warning = FALSE, message = FALSE}
parties %>%
  filter(typenomf == "Woman") %>%
  group_by(year, spouse) %>%
  count() %>%
  ggplot(aes(year,n, color = spouse)) +
  geom_point(alpha = 0.5, size = 3, position = position_jitter(w = 1, h = 0.1)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "Women")


parties %>%
  filter(typenomf == "Man") %>%
  group_by(year, spouse) %>%
  count() %>%
  ggplot(aes(year,n, color = spouse)) +
  geom_point(alpha = 0.5, size = 3, position = position_jitter(w = 1, h = 0.1)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "Men")


```

Gender graphs number of people per year with transaction color 

```{r, echo = FALSE, warning = FALSE, message = FALSE}

parties %>%
  filter(typenomf == "Man") %>%
  group_by(year, transaction) %>%
  count() %>%
  ggplot(aes(year,n, color = transaction, color = gender)) +
  geom_point(alpha = 0.5, size = 2, position = position_jitter(w = 1, h = 0.1))

blah <- parties %>%
  filter(typenomf == "Woman") %>%
  group_by(year, transaction) %>%
  mutate(n = n()) %>%
  ggplot(aes(year,n, color = transaction, color = transaction,text = paste(party1," ", typenomf, " ", side))) +
  geom_point(alpha = 0.5, size = 2, position = position_jitter(w = 1, h = 0.1))

ggplotly(blah, tooltip = "text") 

blogdown::stop_serve()
```


Manly businesses
```{r, echo = FALSE, warning = FALSE, message = FALSE}

parties %>%
  filter(typemf == "MBusiness") %>%
  select(party1,  side, transaction, page) %>%
  knitr::kable()
```


```{r, echo=FALSE, warning=FALSE, message = FALSE}

parties %>%
  filter(typemf == "FBusiness") %>%
  select(party1,  side, transaction, page) %>%
  knitr::kable()
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}
parties %>%
  filter(spouse != "Y", spouse != "F", typenomf == "Woman")
```


```{r, echo = FALSE, warning = FALSE, message = FALSE}

interactive <- parties %>%
  filter(typenomf == "Woman") %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  ggplot(aes(year,count, color = spouse, text = paste(party1," ", side))) +
  geom_point(alpha = 0.5, size = 1.5, position = position_jitter(w = 0.2, h = 0.2)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "Women")

 ggplotly(interactive, tooltip = "text") 

 
 
interactive2 <- parties %>%
  filter(typenomf == "Business") %>%
  group_by(year) %>%
  mutate(count = n()) %>%
  ungroup() %>%
  ggplot(aes(year,count, color = typemf, shape = transaction, text = paste(party1," ", transaction, " ", side))) +
  geom_point(alpha = 0.5, size = 1.5, position = position_jitter(w = 1, h = 1)) +
  scale_color_manual(values=c("red","blue","forestgreen"), labels = c("Misc. Family","Unrelated","Spouse/Partner")) +
  labs(title = "Women")

ggplotly(interactive2, tooltip = "text") 

```
